kernel-module-split: ignore missing dirs
fixes

     0199:    for dir in ["%s/etc/modprobe.d" % (dvar), "%s/etc/modules-load.d" % (dvar), "%s/etc" % (dvar)]:
 *** 0200:        if len(os.listdir(dir)) == 0:
     0201:            os.rmdir(dir)

Exception: FileNotFoundError: [Errno 2] No such file or directory:

Signed-off-by: Enrico Scholz <enrico.scholz@sigma-chemnitz.de>